### PR TITLE
Dynamic layout docs

### PR DESCRIPTION
**Pull request by kquinsland**
I use `cSpell` with vscode.
I have added a few different words to the dictionary:

```json
{
  "cSpell.words": [
    "autodetection",
    "HACS",
    "jsonl",
    "linenums",
    "openhasp",
    "wakeup"
  ]
}
```

I didn't see any IDE specific folders/files in the github repo so I didn't commit the dictionary update. 
Please let me know if i _should_ commit the dictionary update or if I should add `.vscode/*` to the `.gitignore` file before merging this PR.

### CODE REVIEW

**Comment by fvanroie** [comment]
I think adding `.vscode/*` to the `.gitignore` is the best option. I for one don't have the extension enabled in vscode, but we're not pushing any specific IDE for the docs. I'm happy to accept updates, even with occasional spell-errors. We're only human after-all 😃

**Comment by kquinsland** [comment]
> I think adding `.vscode/*` to the `.gitignore` is the best option. I for one don't have the extension enabled in vscode, but we're not pushing any specific IDE for the docs. I'm happy to accept updates, even with occasional spell-errors. We're only human after-all 😃

Figured as much. I held back the `.vscode/settings.json` intentionally for this reason. I can add it to the gitignore to codify this "no IDE specific stuff, please" policy for the repo.... except that would then have an IDE specific file in the repo.

Merge as is or should i push an explicit update to `.gitignore` ?

**Review by fvanroie — APPROVED** [review]

**Review by fvanroie — APPROVED** [review]

**Comment by fvanroie** [comment]
I think `gitignore` can be ammended with `.vscode/*` that should take care of excluding the whole vscode folder.
One think I noticed, since the example relies on `0.7` it shouldn't be pushed to the `0.6.x` docs.
We should update `0.6.x` with the relevant fixes.

I will create a new `0.7.0-dev` repo for changes related to that firmware version.
So I guess I'm suggesting splitting the PR into 2... if you don't mind.

**Review by fvanroie — CHANGES_REQUESTED** [review]
Because the example relies on `0.7` it should be posted against the (upcoming) `0.7` docs branch.
Can you withhold these changes against `0.6` docs for now?

**Comment by kquinsland** [comment]
Sure, ping me here once there's a `0.7` branch and i'll get a new PR in.

#12 is first part

**Comment by fvanroie** [comment]
The spelling errors can go against `0.6` as it would make sense to fix them before creating the new branch.

**Comment by kquinsland** [comment]
Gotcha.

I cherrypicked and now we have #13

**Comment by fvanroie** [comment]
merged

**Comment by kquinsland** [comment]
> merged

ty.

Can you create a `0.7` branch?

**Comment by kquinsland** [comment]
`0.6.3` created, https://github.com/HASwitchPlate/openHASP-docs/pull/14 opened :)

**Pull request closed without merging**
