### PR TITLE
fixed path for weather images

### PR DESCRIPTION
**Pull request by fbonomini**

### CODE REVIEW

**Comment by nagyrobi** [comment]
`L:/` is also correct for image path since v0.6.2.

**Comment by fvanroie** [comment]
Actually for images `L:/` is preferred over `/littlefs/` because it also works on other platforms (PC/Mac/Linux).

- `L:/` uses the LVGL filesystem api, which is platform independent
- `/littlefs/` uses the ESP filesystem api, which only works on ESP

For image.src attributes `/littlefs/` is automatically converted to `L:/` for backwards compatibility,
but new attributes will only support the drive-letter.

Sorry for the confusion. Ideally everything would use `L:/`...

**Review by fvanroie — COMMENTED** [review]
Both work but /littlefs/ is considered to be legacy and will be obsoleted in a future release.

Meanwhile, it is still provided for backwards compatibility but we don't want to promote its use anymore in the documentation. I propose to leave this as-is.

**Comment by fbonomini** [comment]
Thanks!

**Pull request closed without merging**
