### PR TITLE
Update documentation for ESP32-S3-BOX-3

### PR DESCRIPTION
**Pull request by yetanothercarbot**
Updates the documentation to reflect the ESP32-S3-BOX-3 support added in HASwitchPlate/openHASP#774.

Adds a comparison table between the different variations.

### CODE REVIEW

**Comment by fvanroie** [comment]
Thanks

**Comment by jrspowers** [comment]
@yetanothercarbot how can flash the ESP32-S3-BOX-3 can not find file ?

**Comment by jrspowers** [comment]
@yetanothercarbot Could you please send me the file? I can't manage to do it through VSCode, my knowledge isn't quite good enough for that.

**Comment by jrspowers** [comment]
Okay, I understand. Which Discord server is it? I’d definitely like to join there, because I won’t manage it on my own otherwise.

**Comment by jrspowers** [comment]
I’m in! Curious to see if I’ll manage to get it working.

**Pull request merged**
